version: "3.1"

services:
  masterplan-slack:
    image: masterplan-slack
    build: .
    environment:
      - SLACK_TOKEN_MUNBW=${SLACK_TOKEN_MUNBW}
      - SLACK_TOKEN_MUNBB=${SLACK_TOKEN_MUNBB}
      - SLACK_TOKEN_MUNSH=${SLACK_TOKEN_MUNSH}
      - SLACK_TOKEN_DMUN=${SLACK_TOKEN_DMUN}
      - TEST_CHANNEL_MUNBW=${TEST_CHANNEL_MUNBW}
      - TEST_CHANNEL_MUNBB=${TEST_CHANNEL_MUNBB}
      - TEST_CHANNEL_MUNSH=${TEST_CHANNEL_MUNSH}
      - TEST_CHANNEL_DMUN=${TEST_CHANNEL_DMUN}
      - AUTH_EMAIL_HEADER=${AUTH_EMAIL_HEADER:-X-Forwarded-User}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER:-masterplan}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-masterplan}
      - TZ=Europe/Berlin
    ports:
      - 8080:8888
    depends_on:
      - mysql
  #     labels:
  #       - "traefik.enable=true"
  #       - "traefik.docker.network=traefik"
  #       - "traefik.http.routers.masterplan-slack.rule=Host(`masterplan-slack.dmun.de`)"
  #       - "traefik.http.routers.masterplan-slack.entrypoints=websecure"
  #       - "traefik.http.routers.masterplan-slack.tls.certresolver=myresolver"
  #       - "traefik.http.routers.masterplan-slack.middlewares=dmun-team-auth@docker"
  #     networks:
  #       - traefik
  #     restart: unless-stopped

  mysql:
    image: mysql:8.4
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_NAME:-masterplan}
      - MYSQL_USER=${DB_USER:-masterplan}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - masterplan-mysql:/var/lib/mysql
#     restart: unless-stopped

volumes:
  masterplan-mysql:

# networks:
#   traefik:
#     external: true
